# This file was generated by DeltaScope release automation. DO NOT EDIT.
cask "deltascope" do
  version "0.62.0"

  on_macos do
    on_intel do
      url "https://github.com/Fanduzi/DeltaScope/releases/download/v#{version}/deltascope_#{version}_darwin_amd64.tar.gz"
      sha256 "016be382abc98d31f36f2938fb8477bcfc07fcf1d769a6e0db34206fe0b01d50"
    end
    on_arm do
      url "https://github.com/Fanduzi/DeltaScope/releases/download/v#{version}/deltascope_#{version}_darwin_arm64.tar.gz"
      sha256 "f27f40c5a0d2c96bf0db069a3929c9067a41dfcbd043d73499075588a51f1d46"
    end
  end

  name "deltascope"
  desc "Offline SQL review for MySQL, TiDB, and PostgreSQL"
  homepage "https://github.com/Fanduzi/DeltaScope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deltascope"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/deltascope"]
    end
  end
end
