# This file was generated by DeltaScope release automation. DO NOT EDIT.
cask "deltascope" do
  version "0.260.0"

  on_macos do
    on_intel do
      url "https://github.com/Fanduzi/DeltaScope/releases/download/v#{version}/deltascope_#{version}_darwin_amd64.tar.gz"
      sha256 "2db1ff67b55ff63cf1af3af9f397df57f19464d9ab31f0f46cc494de85a1d48b"
    end
    on_arm do
      url "https://github.com/Fanduzi/DeltaScope/releases/download/v#{version}/deltascope_#{version}_darwin_arm64.tar.gz"
      sha256 "ea278d62c631fb7c3ac8883adcb1239d32b2b48d5d6a822b93b74ee53aae7042"
    end
  end

  name "deltascope"
  desc "Offline SQL review for MySQL, TiDB, and PostgreSQL"
  homepage "https://github.com/Fanduzi/DeltaScope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deltascope"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/deltascope"]
    end
  end
end
