# This file was generated by GoReleaser. DO NOT EDIT.
cask "deltascope" do
  version "0.16.3"

  on_macos do
    on_intel do
      url "https://github.com/Fanduzi/DeltaScope/releases/download/v#{version}/deltascope_#{version}_darwin_amd64.tar.gz"
      sha256 "487ae9fb34923c0c5aaf223d034b7c439628989c597119250800769d32679721"
    end
    on_arm do
      url "https://github.com/Fanduzi/DeltaScope/releases/download/v#{version}/deltascope_#{version}_darwin_arm64.tar.gz"
      sha256 "9d59b9f5c3185507a62307d2d3ee311707ca1198a6fca8c6667b274e5291a1e6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Fanduzi/DeltaScope/releases/download/v#{version}/deltascope_#{version}_linux_arm64.tar.gz"
      sha256 "37a0dd51d890b53646c121ead35b2ee4901904a1118a335f69ae4dfd59bf0834"
    end
  end

  name "deltascope"
  desc "Offline SQL review for MySQL and TiDB"
  homepage "https://github.com/Fanduzi/DeltaScope"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deltascope"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/deltascope"]
    end
  end

  # No zap stanza required

end
